### PR TITLE
Fix: Add stored viewController-closure for anyCoordinator

### PR DESCRIPTION
**Pull request by pauljohanneskraft**
This should fix the issue mentioned in https://github.com/quickbirdstudios/XCoordinator/issues/97.

### CODE REVIEW

**Comment by d2vydov** [comment]
thank you!

**Comment by d2vydov** [comment]
just a second - trying test that

**Comment by d2vydov** [comment]
no it doesn't work 😔
`XCoordinator_Example[28842:8291087] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Pushing a navigation controller is not supported'`

**Comment by pauljohanneskraft** [comment]
Ok, I will dive deeper into the issue and update this MR once there is more information available.

**Comment by d2vydov** [comment]
I opened a pull request with example of redirectional coordinator
but without view controller, yet

https://github.com/quickbirdstudios/XCoordinator/pull/99

**Comment by d2vydov** [comment]
oh, I just clear the derived data, tried to test that - it works!

I found out recently about https://github.com/CocoaPods/CocoaPods/issues/8073 and decided to checkout this fix, yeah it works! 😃

**Pull request merged**
